### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Twenty4marc** [BerkeAras/WorkGroup#109]
Hey, can you make an tutorial how to setup workgroup or could you explain how to develope it? I want to help you. Where is the .sql file? I want to upload workgroup on a real shared hosting server. What do I have to do? How to setup the database? ....
Thank you

**Comment by BerkeAras** [comment]
Hey 👋 
Did you already see the installation tutorial? There is no SQL-File. While installing the API (WorkGroup-API) you have the run a migration. This will create the Database-Tables.
You can run WorkGroup on a shared hosting. Just follow the installation at the readme: https://github.com/BerkeAras/WorkGroup#installation 😁

Feel free to comment if you have any problems :)
