### ISSUE TITLE
[BUG]: Emojis are replaced by question marks in the API

### ISSUE THREAD

**Issue by BerkeAras** [BerkeAras/WorkGroup#37]
## Expected Behavior
Emojis should be visible in Post, Comments, ...

## Actual Behavior
Emojis are replaced by question marks in the API

## Steps to Reproduce the Problem

1. Create Post with Emoji
2. See Post

## Critical Bug?

-   [ ] Yes
-   [X] No

## More Information
N/A

**Comment by zikowang** [comment]
see https://github.com/BerkeAras/WorkGroup-API/pull/2
