### ISSUE TITLE
[FEAT]: Add image compression for avatars

### ISSUE THREAD

**Issue by BerkeAras** [BerkeAras/WorkGroup#48]
## Feature Request

**Describe the Feature Request**

Add image compression for avatar-images (serverside)

**Describe Preferred Solution**

N/A

**Describe Alternatives**

N/A

**Related Code**

N/A

**Additional Context**

N/A

**Comment by NotAmmo** [comment]
Nice idea, but what about using Gravatar as well?

**Comment by BerkeAras** [comment]
@NotAmmo Thanks for your reply. Wouldn't it be easier to compress the avatar after uploading it?

**Comment by NotAmmo** [comment]
You could do both. I can only speak for myself that I hate uploading my Avatar on every page. Using gravatar as an external "extra" service would be nice so users can decide whether they want to manually upload their avatar or use their existing avatar from gravatar.

**Comment by BerkeAras** [comment]
Closed: #145 

@NotAmmo WorkGroup is not implementing Gravatar yet. Users can upload their own avatar, and this is being compressed. Soon, administrators will be able to create new users and pre-upload the avatar.
