### ISSUE TITLE
[FEAT]: Improve Login/Register/Reset Screen

### ISSUE THREAD

**Issue by BerkeAras** [BerkeAras/WorkGroup#60]
## Feature Request

**Describe the Feature Request**
Improve the Login/Register or Reset Screen. The current screen is too white and too empty.

**Describe Preferred Solution**
Maybe a big background-image?

**Describe Alternatives**
N/A

**Related Code**
N/A

**Additional Context**

N/A

**Comment by BerkeAras** [comment]
This would be my first suggestion, what do you think?

![workspace_login-min](https://user-images.githubusercontent.com/36629890/117006490-cb695480-ace8-11eb-9a7e-0659cd21cb70.png)

**Comment by JanTrichter** [comment]
This screen is nice but the admin should be able to change the picture or maybe even the layout (e.g log in box centered on page).

**Comment by BerkeAras** [comment]
Fixed with #78
